apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.local.yml convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-api
  name: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose -f docker-compose.local.yml convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: flask-api
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: database-articles
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_USER_PASS
              value: postgres
          image: simple-flask-api-image
          name: simple-flask-api
          ports:
            - containerPort: 8000
          resources: {}
          stdin: true
          tty: true
      hostname: simple-flask-api
      restartPolicy: Always
status: {}
