version: "3.6"

services:
  flask-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: bash
    container_name: simple-fask-api
    image: simple-fask-api-image
    hostname: simple-fask-api
   # user: "damjan"
    environment:
      - DB_USER_PASS=example
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=postgres
    stdin_open: true
    tty: true
    ports:
      - "8000:8000" 
  
  db:
    image: postgis/postgis:10-2.5
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db_data_dump:/db_data_dump
    ports:
      - "5432:5432"   

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080